name: reward
channels:
  - pytorch
  - pytorch3d
  - nvidia
  - conda-forge
dependencies:
  - python=3.10.12
  - pip=22.2.2
  - pytorch=2.5.1
  - torchvision=0.20.1
  - torchaudio=2.5.1
  - pytorch-cuda=12.4
  - numpy=1.26.4
  - stable-baselines3
  - pip:
    # Install latest main branches from these repositories (explicit branch improves reproducibility)
    - git+https://github.com/ARISE-Initiative/robosuite.git
    - git+https://github.com/ARISE-Initiative/robomimic.git